try:
    num=2
    num1=2
    print(num1+num)
except Exception as e:
    print(e)
